### ISSUE TITLE
ARM64 Docker Image Build?

### ISSUE THREAD

**Issue by geerlingguy** [danopstech/starlink_exporter#1]
**Is your feature request related to a problem? Please describe.**

I tried running your pre-build Docker image on a Raspberry Pi... but it unfortunately didn't work.

**Describe the solution you'd like**

It would be really amazing if you could use the GitHub Actions BuildX action to build a cross-platform Docker image (see an example in action here: https://github.com/geerlingguy/docker-debian10-ansible/blob/master/.github/workflows/build.yml#L53

**Describe alternatives you've considered**

I could set up an X86 server instead, but that makes me sad. I could also build my own Docker image based on an ARM64 base image instead, but that means I have to basically maintain a forked image.

**Additional context**

I loved your post on Reddit, and have been trying to beef up my own in-home monitoring. I'd love to have a dashboard like yours set up so I can have some really good data available for my full Starlink review in a few weeks.

**Comment by geerlingguy** [comment]
(Another alternative is I could just download and run the binary, but then I would have something not-inside-Docker in my config...).

**Comment by dwillcocks** [comment]
@geerlingguy I have pushed ARMv7 and ARM64 docker images "latest" & "v0.0.2" to both Dockerhub and ghcr. Unfortunately I have no ARM devices to test with, can you test?

**Comment by geerlingguy** [comment]
@dwillcocks - Gladly! I'll test it in a little bit and let you know how it goes.

**Comment by geerlingguy** [comment]
Looks like it's working perfectly!

```
$ curl localhost:9817/metrics
# HELP starlink_dish_alert_mast_not_near_vertical Status of mast position
# TYPE starlink_dish_alert_mast_not_near_vertical gauge
starlink_dish_alert_mast_not_near_vertical 0
# HELP starlink_dish_alert_motors_stuck Status of motor stuck
# TYPE starlink_dish_alert_motors_stuck gauge
starlink_dish_alert_motors_stuck 0
# HELP starlink_dish_alert_slow_eth_speeds Status of ethernet
# TYPE starlink_dish_alert_slow_eth_speeds gauge
starlink_dish_alert_slow_eth_speeds 0
# HELP starlink_dish_alert_thermal_shutdown Status of thermal shutdown
# TYPE starlink_dish_alert_thermal_shutdown gauge
starlink_dish_alert_thermal_shutdown 0
# HELP starlink_dish_alert_thermal_throttle Status of thermal throttling
# TYPE starlink_dish_alert_thermal_throttle gauge
starlink_dish_alert_thermal_throttle 0
# HELP starlink_dish_alert_unexpected_location Status of location
# TYPE starlink_dish_alert_unexpected_location gauge
starlink_dish_alert_unexpected_location 0
# HELP starlink_dish_currently_obstructed Status of view of the sky
# TYPE starlink_dish_currently_obstructed gauge
starlink_dish_currently_obstructed 0
# HELP starlink_dish_downlink_throughput_bytes Amount of bandwidth in bytes per second download
# TYPE starlink_dish_downlink_throughput_bytes gauge
starlink_dish_downlink_throughput_bytes 2.00800625e+06
# HELP starlink_dish_first_nonempty_slot_seconds Seconds to next non empty slot
# TYPE starlink_dish_first_nonempty_slot_seconds gauge
starlink_dish_first_nonempty_slot_seconds 0
# HELP starlink_dish_fraction_obstruction_ratio Percentage of obstruction
# TYPE starlink_dish_fraction_obstruction_ratio gauge
starlink_dish_fraction_obstruction_ratio 0.14223024249076843
# HELP starlink_dish_info Running software versions and IDs of hardware
# TYPE starlink_dish_info gauge
starlink_dish_info{country_code="US",device_id="ut01000000-00000000-0000f0c4",hardware_version="rev1_pre_production",software_version="feb4dfde-e080-4e6a-bcbe-21511ee9c8bc.release",utc_offset="-21599"} 1
# HELP starlink_dish_last_24h_obstructed_seconds Number of seconds view of sky has been obstructed in the last 24hours
# TYPE starlink_dish_last_24h_obstructed_seconds gauge
starlink_dish_last_24h_obstructed_seconds 6356
# HELP starlink_dish_pop_ping_drop_ratio Percent of pings dropped
# TYPE starlink_dish_pop_ping_drop_ratio gauge
starlink_dish_pop_ping_drop_ratio 0
# HELP starlink_dish_pop_ping_latency_seconds Latency of connection in seconds
# TYPE starlink_dish_pop_ping_latency_seconds gauge
starlink_dish_pop_ping_latency_seconds 0.03266666829586029
# HELP starlink_dish_scrape_duration_seconds Time to scrape metrics from starlink dish
# TYPE starlink_dish_scrape_duration_seconds gauge
starlink_dish_scrape_duration_seconds 0.01776572
# HELP starlink_dish_snr Signal strength of the connection
# TYPE starlink_dish_snr gauge
starlink_dish_snr 9
# HELP starlink_dish_state The current dishState of the Dish (Unknown, Booting, Searching, Connected).
# TYPE starlink_dish_state gauge
starlink_dish_state 1
# HELP starlink_dish_up Was the last query of Starlink dish successful.
# TYPE starlink_dish_up gauge
starlink_dish_up 1
# HELP starlink_dish_uplink_throughput_bytes Amount of bandwidth in bytes per second upload
# TYPE starlink_dish_uplink_throughput_bytes gauge
starlink_dish_uplink_throughput_bytes 60775.46484375
# HELP starlink_dish_uptime_seconds Dish running time
# TYPE starlink_dish_uptime_seconds gauge
starlink_dish_uptime_seconds 291375
# HELP starlink_dish_valid_seconds Unknown
# TYPE starlink_dish_valid_seconds gauge
starlink_dish_valid_seconds 61618.76171875
# HELP starlink_dish_wedge_abs_fraction_obstruction_ratio Percentage of Absolute fraction per wedge section
# TYPE starlink_dish_wedge_abs_fraction_obstruction_ratio gauge
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="0"} 0.044917866587638855
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="1"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="10"} 0.044958289712667465
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="11"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="2"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="3"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="4"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="5"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="6"} 0
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="7"} 0.0012710301671177149
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="8"} 0.009389301761984825
starlink_dish_wedge_abs_fraction_obstruction_ratio{wedge="9"} 0.041693754494190216
# HELP starlink_dish_wedge_fraction_obstruction_ratio Percentage of obstruction per wedge section
# TYPE starlink_dish_wedge_fraction_obstruction_ratio gauge
starlink_dish_wedge_fraction_obstruction_ratio{wedge="0"} 0.2343340814113617
starlink_dish_wedge_fraction_obstruction_ratio{wedge="1"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="10"} 0.31473639607429504
starlink_dish_wedge_fraction_obstruction_ratio{wedge="11"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="2"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="3"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="4"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="5"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="6"} 0
starlink_dish_wedge_fraction_obstruction_ratio{wedge="7"} 0.0697559118270874
starlink_dish_wedge_fraction_obstruction_ratio{wedge="8"} 0.3449874222278595
starlink_dish_wedge_fraction_obstruction_ratio{wedge="9"} 0.5921974182128906
```

This is running on the Pi OS 64-bit beta:

```
$ uname -a
Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
```

But it should also be working on 32-bit (I don't see anything weird about that image build that would throw it off.

Thanks again for this excellent little project, and I would be happy to give you a plug in the video I eventually make for my own Starlink review — would you rather I point people here... your YouTube channel... etc.?

(And finally, I'd love to drop a donation somewhere if you have a tip jar, sponsors account, etc. — this saved me a good deal of time in building a few metrics I wanted to get at.)

**Comment by dwillcocks** [comment]
Excellent, goreleaser to the rescue! and first issue done!

> This is running on the Pi OS 64-bit beta:
> But it should also be working on 32-bit (I don't see anything weird about that image build that would throw it off.

Its hard to find but I believe the later Pis run ARM64v8, and older generations would need the ARMv7 build.

> and I would be happy to give you a plug in the video I eventually make for my own Starlink review — would you rather I point people here... your YouTube channel... etc.?

I think Github would be the best place to point people as I have not started my adventure into Youtube yet, just grabbed the channel name, its another project in the backlog.

> (And finally, I'd love to drop a donation somewhere if you have a tip jar, sponsors account, etc. — this saved me a good deal of time in building a few metrics I wanted to get at.)

This is my first ever public repo to share my work, I will look into Github sponsors. but currently I have nothing setup.

**Comment by geerlingguy** [comment]
> Its hard to find but I believe the later Pis run ARM64v8, and older generations would need the ARMv7 build.

The Pis since the Pi 2 model B have 64-bit capable processors, but right now the default for all Pis (even the newest 4-core chips) is to run the 32-bit OS, as the 64-bit Pi OS is still marked as 'beta' :(

I hope that changes someday soon, though. Targeting ARMv7 can be a bit tricky with some software!
