### ISSUE TITLE
Collect new data in 6390f89c-448c-4fe6-8e1c-14708993ef7c.uterm.release

### ISSUE THREAD

**Issue by virtuallynathan** [danopstech/starlink_exporter#38]
New fields added to getDishStatus, would be good to have collected

"avgProlongedObstructionDurationS": 0.905022,
"avgProlongedObstructionIntervalS": 459.4299,
"boresightAzimuthDeg": 0.587069,
"boresightElevationDeg": 67.196815

**Comment by dwillcocks** [comment]
I have not upgraded to 8993ef7c yet, I will collected theses soon as my dish has upgraded.

**Comment by dwillcocks** [comment]
https://github.com/danopstech/starlink_exporter/releases/tag/v0.0.5

**Comment by virtuallynathan** [comment]
Awesome, just upgraded!
